// <auto-generated />
namespace BalangaAMS.DataLayer.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddedChurchIdAndOtherLocalTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedChurchIdAndOtherLocalTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201708281234305_-AddedChurchIdAndOtherLocalTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
